#!/usr/bin/env python3
"""Curated Yahoo-ticker -> company name map for Tradegate name-search resolution."""

NAME_MAP = {
    # --- US ---
    "AAPL": "Apple Inc", "MSFT": "Microsoft Corp", "NVDA": "Nvidia Corp",
    "GOOGL": "Alphabet Inc", "AMZN": "Amazon.com Inc", "META": "Meta Platforms Inc",
    "AVGO": "Broadcom Inc", "TSLA": "Tesla Inc", "AMD": "Advanced Micro Devices",
    "CRM": "Salesforce Inc", "ORCL": "Oracle Corp", "ADBE": "Adobe Inc",
    "NOW": "ServiceNow Inc", "INTU": "Intuit Inc", "QCOM": "Qualcomm Inc",
    "TXN": "Texas Instruments", "MU": "Micron Technology", "AMAT": "Applied Materials",
    "LRCX": "Lam Research", "KLAC": "KLA Corp", "ASML": "ASML Holding",
    "PANW": "Palo Alto Networks", "CRWD": "CrowdStrike Holdings", "ZS": "Zscaler Inc",
    "FTNT": "Fortinet Inc", "NET": "Cloudflare Inc", "DDOG": "Datadog Inc",
    "SNOW": "Snowflake Inc", "MDB": "MongoDB Inc", "PLTR": "Palantir Technologies",
    "APP": "Applovin Corp", "NFLX": "Netflix Inc", "BKNG": "Booking Holdings",
    "ABNB": "Airbnb Inc", "UBER": "Uber Technologies", "DASH": "DoorDash Inc",
    "SPOT": "Spotify Technology", "ADSK": "Autodesk Inc", "PAYX": "Paychex Inc",
    "ADP": "Automatic Data Processing", "INTC": "Intel Corp", "MRVL": "Marvell Technology",
    "ON": "ON Semiconductor", "ARM": "Arm Holdings", "ANET": "Arista Networks",
    "VRT": "Vertiv Holdings", "COHR": "Coherent Corp", "CIEN": "Ciena Corp",
    "DELL": "Dell Technologies", "HPQ": "HP Inc", "CSCO": "Cisco Systems",
    "IBM": "IBM", "ACN": "Accenture", "BRZE": "Braze Inc", "HUBS": "HubSpot Inc",
    "TEAM": "Atlassian Corp", "MNDY": "Monday.com Ltd", "HOOD": "Robinhood Markets",
    "COIN": "Coinbase Global", "RBLX": "Roblox Corp", "ROKU": "Roku Inc",
    "DUOL": "Duolingo Inc", "TTD": "Trade Desk Inc", "SE": "Sea Ltd",
    "BROS": "Dutch Bros Inc", "ALAB": "Astera Labs Inc", "CRDO": "Credo Technology",
    "NBIS": "Nebius Group", "IONQ": "IonQ Inc", "RGTI": "Rigetti Computing",
    "QBTS": "D-Wave Quantum", "AXON": "Axon Enterprise", "KTOS": "Kratos Defense",
    "LUNR": "Intuitive Machines", "RDW": "Redwire Corp", "NKE": "Nike Inc",
    "LULU": "Lululemon Athletica", "SBUX": "Starbucks Corp", "CMG": "Chipotle Mexican Grill",
    "YUM": "Yum Brands Inc", "MCD": "McDonald's Corp", "DIS": "Walt Disney Co",
    "CHTR": "Charter Communications", "LYV": "Live Nation Entertainment",
    "TDG": "TransDigm Group", "HEI": "Heico Corp", "HWM": "Howmet Aerospace",
    "CAT": "Caterpillar Inc", "DE": "Deere & Co", "PCAR": "PACCAR Inc",
    "EMR": "Emerson Electric", "ETN": "Eaton Corp", "ROK": "Rockwell Automation",
    "PH": "Parker Hannifin", "ITW": "Illinois Tool Works", "MLM": "Martin Marietta Materials",
    "UNP": "Union Pacific", "NSC": "Norfolk Southern", "FDX": "FedEx Corp",
    "MATX": "Matson Inc", "WAB": "Wabtec Corp",
    # --- DE (DAX 40) ---
    "SAP.DE": "SAP SE", "SIE.DE": "Siemens AG",
    "AIR.DE": "Airbus", "BMW.DE": "BMW", "MBG.DE": "Mercedes-Benz",
    "VOW3.DE": "Volkswagen", "BAS.DE": "BASF", "BAYN.DE": "Bayer",
    "DTE.DE": "Deutsche Telekom", "IFX.DE": "Infineon",
    "INS.DE": "Deutsche Boerse", "MUV2.DE": "Muenchener Rueck", "DPG.DE": "Deutsche Post",
    "RWE.DE": "RWE", "ALV.DE": "Allianz", "1AT1.DE": "Amadeus",
    "P911.DE": "PUMA", "RHM.DE": "Rheinmetall", "MTX.DE": "MTU Aero Engines",
    "NEM.DE": "Nemetschek", "ZAL.DE": "Zalando", "SCA.DE": "Sartorius AG",
    "DD1.DE": "HelloFresh", "CYR.DE": "cyan AG", "AIXA.DE": "Aixtron",
    "DTG.DE": "Daimler Truck", "FME.DE": "Fresenius Medical", "HEG.DE": "Hensoldt",
    "HNR1.DE": "Hannover Rueck", "KBX.DE": "Knorr-Bremse", "LEG.DE": "LEG Immobilien",
    "NRK.DE": "Nordex", "PAP.DE": "Porsche Automobil", "QIA.DE": "QIAGEN",
    "R3N.DE": "Evonik", "SRT.DE": "Sartorius", "ST1.DE": "StoneCo",
    "SY1.DE": "Symrise", "TLG.DE": "ThyssenKrupp", "UNA.DE": "Uniper",
    "WCH.DE": "Wacker Chemie",
}
# entries that will likely fail and should be dropped from universe if unresolved:
# DTG.DE, LEG.DE, R3N.DE, ST1.DE, WCH.DE, SRT.DE(DE-listed?) etc.
